// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: redis/src/leaderboard/proto/submission.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Submission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QuestionId    int32                  `protobuf:"varint,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_redis_src_leaderboard_proto_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_redis_src_leaderboard_proto_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_redis_src_leaderboard_proto_submission_proto_rawDescGZIP(), []int{0}
}

func (x *Submission) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Submission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Submission) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *Submission) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Submission) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_redis_src_leaderboard_proto_submission_proto protoreflect.FileDescriptor

const file_redis_src_leaderboard_proto_submission_proto_rawDesc = "" +
	"\n" +
	",redis/src/leaderboard/proto/submission.proto\x12\vleaderboard\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\n" +
	"Submission\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\x05R\n" +
	"questionId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB?Z=github.com/Darrekt/swe-playground/redis/src/leaderboard/protob\x06proto3"

var (
	file_redis_src_leaderboard_proto_submission_proto_rawDescOnce sync.Once
	file_redis_src_leaderboard_proto_submission_proto_rawDescData []byte
)

func file_redis_src_leaderboard_proto_submission_proto_rawDescGZIP() []byte {
	file_redis_src_leaderboard_proto_submission_proto_rawDescOnce.Do(func() {
		file_redis_src_leaderboard_proto_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_src_leaderboard_proto_submission_proto_rawDesc), len(file_redis_src_leaderboard_proto_submission_proto_rawDesc)))
	})
	return file_redis_src_leaderboard_proto_submission_proto_rawDescData
}

var file_redis_src_leaderboard_proto_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_redis_src_leaderboard_proto_submission_proto_goTypes = []any{
	(*Submission)(nil),            // 0: leaderboard.Submission
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_redis_src_leaderboard_proto_submission_proto_depIdxs = []int32{
	1, // 0: leaderboard.Submission.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_redis_src_leaderboard_proto_submission_proto_init() }
func file_redis_src_leaderboard_proto_submission_proto_init() {
	if File_redis_src_leaderboard_proto_submission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_src_leaderboard_proto_submission_proto_rawDesc), len(file_redis_src_leaderboard_proto_submission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_src_leaderboard_proto_submission_proto_goTypes,
		DependencyIndexes: file_redis_src_leaderboard_proto_submission_proto_depIdxs,
		MessageInfos:      file_redis_src_leaderboard_proto_submission_proto_msgTypes,
	}.Build()
	File_redis_src_leaderboard_proto_submission_proto = out.File
	file_redis_src_leaderboard_proto_submission_proto_goTypes = nil
	file_redis_src_leaderboard_proto_submission_proto_depIdxs = nil
}
