networks:
  redis-net:

services:
  client:
    container_name: client
    image: golang:1.24
    entrypoint: ["sleep", "infinity"]
    # entrypoint: ["go", "run", "main.go", "leaderboard-client"]
    environment:
      - SWE_SERVER_HOST=server
      - SWE_SERVER_PORT=80
    volumes:
      - ./src:/opt/client:Z
    security_opt:
      - label=disable
    working_dir: /opt/client
    networks: 
      - redis-net
  server:
    container_name: server
    image: golang:1.24
    entrypoint: ["go", "run", "main.go", "leaderboard-server"]
    environment:
      - SWE_SERVER_PORT=80
      - SWE_REDIS_HOST=redis
      - SWE_REDIS_PORT=6379
    volumes:
      - ./src:/opt/server:Z
    working_dir: /opt/server
    networks: 
      - redis-net
    security_opt:
      - label=disable
  redis:
    container_name: redis
    image: redis:latest
    networks: 
      - redis-net
      